FROM apache/airflow:2.7.0

USER root
# Install system deps
RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ git && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt

# Ensure src and dags are under /opt/airflow (this will be mounted by compose)
