stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/Events.csv
    - data/raw/Fighters.csv
    - data/raw/Fights.csv
    - data/raw/Fstats.csv
    - src/preprocess.py
    outs:
    - data/processed/events_processed.csv
    - data/processed/fighters_processed.csv
    - data/processed/fights_processed.csv
    - data/processed/fstats_processed.csv
