stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/cards_sample.csv
    - src/preprocess.py
    outs:
    - data/processed/processed.csv
  train_rl:
    cmd: python src/train.py
    deps:
    - Core/agents.py
    - Core/demo.py
    - src/train.py
    outs:
    - replays
    - rl_agent_model.pth
