stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/delays.csv
      - params.yaml
    outs:
      - data/processed/delays.csv
    params:
      - preprocess
      - encoding
      - scaling

  split:
    cmd: python src/split_data.py --config params.yaml
    deps:
      - src/split_data.py
      - data/processed/delays.csv
      - params.yaml
    outs:
      - data/split/train.csv
      - data/split/test.csv
      - data/split/val.csv
    params:
      - preprocess.test_size
      - preprocess.val_size
      - preprocess.random_state

  train_baseline:
    cmd: python src/train.py --config params.yaml
    deps:
      - src/train.py
      - data/split/train.csv
      - data/split/test.csv
      - data/split/val.csv
      - params.yaml
    outs:
      - models/TrainDelayPrediction.keras

  evaluate_baseline:
    cmd: python src/evaluate.py --model_path models/TrainDelayPrediction.keras --config params.yaml
    deps:
      - src/evaluate.py
      - data/split/train.csv
      - data/split/val.csv
      - params.yaml
      - models/TrainDelayPrediction.keras
    metrics:
      - reports/eval.json:
          cache: false
