stages:
  preprocess:
    cmd: python src/preprocess.py --config params.yaml
    deps:
      - src/preprocess.py
      - data/raw/dataset.csv
      - params.yaml
    outs:
      - data/processed/dataset.csv
      - models/encoders.pkl
      - models/scaler.pkl
    params:
      - preprocess
      - encoding
      - scaling

  split:
    cmd: python src/split_data.py --config params.yaml
    deps:
      - src/split_data.py
      - data/processed/dataset.csv
      - params.yaml
    outs:
      - data/split/X_train.csv
      - data/split/X_test.csv
      - data/split/y_train.csv
      - data/split/y_test.csv
    params:
      - preprocess.test_size
      - preprocess.random_state
